/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

/**
 *
 * @author Anézio
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame_BemVindo = new javax.swing.JInternalFrame();
        jPanel_Internal = new javax.swing.JPanel();
        jButton_CadClientes = new javax.swing.JButton();
        jButton_CadFornecedores = new javax.swing.JButton();
        jButton_Funcionarios = new javax.swing.JButton();
        jButton_CadMaterial = new javax.swing.JButton();
        jButton_FecharBemVindo = new javax.swing.JButton();
        jLabel_PainelFundo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_FundoPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_Cadastro = new javax.swing.JMenu();
        jMenuItem_Clientes = new javax.swing.JMenuItem();
        jMenuItem_Fornecedores = new javax.swing.JMenuItem();
        jMenuItem_Funcionarios = new javax.swing.JMenuItem();
        jMenuItem_Material = new javax.swing.JMenuItem();
        jMenu_Relatorios = new javax.swing.JMenu();
        jMenu_Ferramentas = new javax.swing.JMenu();
        jMenuItem_TelaBemVindos = new javax.swing.JMenuItem();
        jMenu_Sair = new javax.swing.JMenu();
        jMenuItem_Sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrame_BemVindo.setTitle("Bem vindo!");
        jInternalFrame_BemVindo.setPreferredSize(new java.awt.Dimension(670, 64));
        jInternalFrame_BemVindo.setVisible(true);
        jInternalFrame_BemVindo.getContentPane().setLayout(null);

        jPanel_Internal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel_Internal.setLayout(null);

        jButton_CadClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo_clientes.png"))); // NOI18N
        jButton_CadClientes.setToolTipText("Clientes");
        jButton_CadClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton_CadClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CadClientesActionPerformed(evt);
            }
        });
        jPanel_Internal.add(jButton_CadClientes);
        jButton_CadClientes.setBounds(40, 50, 47, 47);

        jButton_CadFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Fornecedores.png"))); // NOI18N
        jButton_CadFornecedores.setToolTipText("Fornecedores");
        jButton_CadFornecedores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_Internal.add(jButton_CadFornecedores);
        jButton_CadFornecedores.setBounds(170, 50, 50, 50);

        jButton_Funcionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Funcionários.png"))); // NOI18N
        jButton_Funcionarios.setToolTipText("Funcionários");
        jButton_Funcionarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_Internal.add(jButton_Funcionarios);
        jButton_Funcionarios.setBounds(40, 160, 47, 50);

        jButton_CadMaterial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/material.jpg"))); // NOI18N
        jButton_CadMaterial.setToolTipText("Material");
        jButton_CadMaterial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton_CadMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CadMaterialActionPerformed(evt);
            }
        });
        jPanel_Internal.add(jButton_CadMaterial);
        jButton_CadMaterial.setBounds(170, 160, 50, 50);

        jButton_FecharBemVindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/exit.png"))); // NOI18N
        jButton_FecharBemVindo.setToolTipText("Fechar tela bem-vindo");
        jButton_FecharBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FecharBemVindoActionPerformed(evt);
            }
        });
        jPanel_Internal.add(jButton_FecharBemVindo);
        jButton_FecharBemVindo.setBounds(610, 10, 40, 40);

        jLabel_PainelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/internalframe1.png"))); // NOI18N
        jPanel_Internal.add(jLabel_PainelFundo);
        jLabel_PainelFundo.setBounds(20, 10, 630, 240);

        jInternalFrame_BemVindo.getContentPane().add(jPanel_Internal);
        jPanel_Internal.setBounds(-10, 40, 660, 260);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel1.setText("Sistema de Gerenciamento de Pessoal e Controle de Estoque");
        jInternalFrame_BemVindo.getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 0, 490, 30);

        getContentPane().add(jInternalFrame_BemVindo);
        jInternalFrame_BemVindo.setBounds(0, 20, 660, 330);

        jLabel_FundoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo_telaprincipal.jpg"))); // NOI18N
        getContentPane().add(jLabel_FundoPrincipal);
        jLabel_FundoPrincipal.setBounds(0, 16, 660, 330);

        jMenu_Cadastro.setText("Cadastro");

        jMenuItem_Clientes.setText("Clientes");
        jMenuItem_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ClientesActionPerformed(evt);
            }
        });
        jMenu_Cadastro.add(jMenuItem_Clientes);

        jMenuItem_Fornecedores.setText("Fornecedores");
        jMenu_Cadastro.add(jMenuItem_Fornecedores);

        jMenuItem_Funcionarios.setText("Funcionários");
        jMenu_Cadastro.add(jMenuItem_Funcionarios);

        jMenuItem_Material.setText("Material");
        jMenu_Cadastro.add(jMenuItem_Material);

        jMenuBar1.add(jMenu_Cadastro);

        jMenu_Relatorios.setText("Relatórios");
        jMenuBar1.add(jMenu_Relatorios);

        jMenu_Ferramentas.setText("Ferramentas");

        jMenuItem_TelaBemVindos.setText("Tela Bem-Vindo");
        jMenuItem_TelaBemVindos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_TelaBemVindosActionPerformed(evt);
            }
        });
        jMenu_Ferramentas.add(jMenuItem_TelaBemVindos);

        jMenuBar1.add(jMenu_Ferramentas);

        jMenu_Sair.setText("Sair");

        jMenuItem_Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/exit.png"))); // NOI18N
        jMenuItem_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_SairActionPerformed(evt);
            }
        });
        jMenu_Sair.add(jMenuItem_Sair);

        jMenuBar1.add(jMenu_Sair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(677, 412));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_TelaBemVindosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_TelaBemVindosActionPerformed
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem_TelaBemVindosActionPerformed

    private void jButton_CadClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CadClientesActionPerformed
        TelaClientes tela = new TelaClientes();
        tela.setVisible(true);
    }//GEN-LAST:event_jButton_CadClientesActionPerformed

    private void jButton_CadMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CadMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_CadMaterialActionPerformed

    private void jButton_FecharBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FecharBemVindoActionPerformed
        jInternalFrame_BemVindo.dispose();
    }//GEN-LAST:event_jButton_FecharBemVindoActionPerformed

    private void jMenuItem_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_SairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem_SairActionPerformed

    private void jMenuItem_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ClientesActionPerformed
        TelaClientes tela = new TelaClientes();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem_ClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_CadClientes;
    private javax.swing.JButton jButton_CadFornecedores;
    private javax.swing.JButton jButton_CadMaterial;
    private javax.swing.JButton jButton_FecharBemVindo;
    private javax.swing.JButton jButton_Funcionarios;
    private javax.swing.JInternalFrame jInternalFrame_BemVindo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_FundoPrincipal;
    private javax.swing.JLabel jLabel_PainelFundo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_Clientes;
    private javax.swing.JMenuItem jMenuItem_Fornecedores;
    private javax.swing.JMenuItem jMenuItem_Funcionarios;
    private javax.swing.JMenuItem jMenuItem_Material;
    private javax.swing.JMenuItem jMenuItem_Sair;
    private javax.swing.JMenuItem jMenuItem_TelaBemVindos;
    private javax.swing.JMenu jMenu_Cadastro;
    private javax.swing.JMenu jMenu_Ferramentas;
    private javax.swing.JMenu jMenu_Relatorios;
    private javax.swing.JMenu jMenu_Sair;
    private javax.swing.JPanel jPanel_Internal;
    // End of variables declaration//GEN-END:variables
}
