/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import javax.swing.JOptionPane;

/**
 *
 * @author Anézio
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Usuario = new javax.swing.JLabel();
        jTextField_Usuario = new javax.swing.JTextField();
        jPasswordField_Senha = new javax.swing.JPasswordField();
        jButton_Acessar = new javax.swing.JButton();
        jButton_Sair = new javax.swing.JButton();
        jLabel_Senha = new javax.swing.JLabel();
        jLabel_TelaFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel_Usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Usuario.setText("Usuário:");
        getContentPane().add(jLabel_Usuario);
        jLabel_Usuario.setBounds(50, 60, 60, 40);
        getContentPane().add(jTextField_Usuario);
        jTextField_Usuario.setBounds(130, 70, 170, 20);
        getContentPane().add(jPasswordField_Senha);
        jPasswordField_Senha.setBounds(130, 110, 170, 20);

        jButton_Acessar.setText("Acessar");
        jButton_Acessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AcessarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Acessar);
        jButton_Acessar.setBounds(141, 160, 80, 23);

        jButton_Sair.setText("Sair");
        jButton_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SairActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Sair);
        jButton_Sair.setBounds(240, 160, 51, 23);

        jLabel_Senha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Senha.setText("Senha:");
        getContentPane().add(jLabel_Senha);
        jLabel_Senha.setBounds(60, 100, 50, 40);

        jLabel_TelaFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/FundoTelaLogin.jpg"))); // NOI18N
        getContentPane().add(jLabel_TelaFundo);
        jLabel_TelaFundo.setBounds(0, 0, 400, 250);

        setSize(new java.awt.Dimension(416, 287));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AcessarActionPerformed
        if(jTextField_Usuario.getText().equals("admin") && jPasswordField_Senha.getText().equals("admin")){
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
        dispose();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Usuário ou senha inválidos.");
            jTextField_Usuario.setText("");
            jPasswordField_Senha.setText("");
        }
    }//GEN-LAST:event_jButton_AcessarActionPerformed

    private void jButton_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton_SairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Acessar;
    private javax.swing.JButton jButton_Sair;
    private javax.swing.JLabel jLabel_Senha;
    private javax.swing.JLabel jLabel_TelaFundo;
    private javax.swing.JLabel jLabel_Usuario;
    private javax.swing.JPasswordField jPasswordField_Senha;
    private javax.swing.JTextField jTextField_Usuario;
    // End of variables declaration//GEN-END:variables
}
